# Generated by Django 3.1 on 2020-08-21 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('initial', models.CharField(max_length=3, unique=True)),
                ('is_user', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
