# Generated by Django 3.1 on 2020-09-19 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfassstatus', models.CharField(max_length=255)),
                ('attendance', models.CharField(max_length=255)),
                ('reasonNotPresent', models.CharField(max_length=255)),
                ('otherNotPresent', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('sickChoices', models.CharField(max_length=255)),
                ('otherSicks', models.CharField(max_length=255)),
                ('work_status', models.CharField(max_length=255)),
                ('wfo_description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
