# Generated by Django 3.1 on 2020-09-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='selfassstatus',
            field=models.CharField(max_length=251),
        ),
    ]
